extends Node

var COL_LAYERS = {
	WORLD_LAYER = 0x01,
	SELECTION_LAYER = 0x02,
	VISIBILITY_LAYER = 0x04,
	RESOURCE_LAYER = 0x08,
	BULLET_LAYER = 0x10,
	BUILD_RANGE_LAYER = 0x20,
	SHIELD_LAYER = 0x40
}

var Z_LAYERS = {
	TERRAIN_Z = 0,
	WIRE_Z = 1,
	HUB_Z = 2,
	
	FOG_OF_WAR_BUFF_Z = 7,
	FOG_OF_WAR_Z = 8,
	FOG_OF_WAR_TRANS_Z = 9,
	
	RADAR_SIG_Z = 13,
	BULLET_Z = 14,
	SHIELD_Z = 15,
	
	WEAP_RANGE_BUFF_Z = 19,
	WEAP_RANGE_RING_Z = 20,
	WEAP_RANGE_TRANS_Z = 21,
	
	BUILDING_RANGE_BUFF_Z = 25,
	BUILDING_RANGE_RING_Z = 26,
	BUILDING_RANGE_TRANS_Z = 27,
	
	RADAR_BUFF_Z = 31,
	RADAR_RING_Z = 32,
	RADAR_TRANS_Z = 33
}

func _ready():
	Globals.set("PLAYER_TEAM", "Team_1")
	for c in COL_LAYERS:
		Globals.set(c, COL_LAYERS[c])
	
	for z in Z_LAYERS:
		Globals.set(z, Z_LAYERS[z])